Add basic working early bootstrap.

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -6,12 +6,26 @@ run() {
     "$@"
 }
 
+# we shouldn't be root when running this
+if [ "$(id -u)" -eq 0 ]; then
+    echo "error: this script should not be run as root"
+    exit 1
+fi
+
+# turn on filevault if it's not on
+if ! run fdesetup isactive; then
+    echo "Full disk encryption is not active"
+    read -p "Press enter to immediately restart to enable..." ans
+    run sudo fdesetup enable -user $USER -forcerestart
+fi
+
 trap 'echo ERROR' EXIT
 
+# enable SSH
 run systemsetup -setremotelogin on
 
 # SSH key doesn't exist until we hit the SSH server for the first time
-nc -z localhost 22
+echo hello | run nc -z localhost 22
 
 if ! which sixword >/dev/null; then
     run sudo gem install sixword
@@ -26,4 +40,13 @@ done
 echo "SSH key fingerprint:"
 ssh-keygen -lf /etc/ssh_host_rsa_key.pub | cut -d' ' -f2 | sixword -H
 
+echo 'Please run `yoyo init-ssh ...` on the credentialer machine'
+read -p "Press enter when finished..." ans
+
+run sudo mkdir -vp ~root/.ssh
+run sudo cp -v ~/.ssh/authorized_keys ~root/.ssh/
+
 trap - EXIT
+
+echo "Yoyo is now set up and ready to run!"
+echo 'Please run `yoyo spinup ...` on the credentialer machine'
